name: Test Python App
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.7'
          architecture: x64
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: python -m pip install -U pip && pip install -r requirements-dev.txt
      - name: Security Test
        run: python -m bandit -r app/
      - name: Lint Test
        run: python -m flake8 app/
      - name: Unit Test
        run: python -m pytest -v
